[redis]
host = "127.0.0.1"
port = 6379
db = 0

[kafka]
host = "172.27.237.77"  # wsl
#host = "172.17.160.199" # aliyun
port = 9092

[kafka.scrapy]
topic="scrapy_data_1"
key="an"

[kafka.spark]
topic="scrapy_data_2"

[debug]
#enable = true
enable = false